import type { Property, Conversation, DalkaAlert, User } from "./types";

export const DEMO_AGENT: User = {
  id: "agent-1",
  email: "agent@dalka.com",
  name: "Ayaan Maxamed",
  phone: "+252 61 234 5678",
  role: "agent",
  bio: "Dallaal hanti-ma-guurto ah oo ka caawiya macaamiisha helitaanka guryo ku habboon.",
  savedSearches: [],
  bookmarks: [],
};

export const SEED_PROPERTIES: Property[] = [
  {
    id: "prop-1",
    title: "Guri dabaq casri ah - Hodan",
    description: "Guri dabaq casri ah oo ku yaal degmada Hodan, una dhow dugsiyo, suuqyo iyo waddooyinka waaweyn.",
    price: 185000,
    type: "penthouse",
    listingType: "sale",
    bedrooms: 3,
    bathrooms: 2,
    area: 245,
    address: "Degmada Hodan",
    city: "Muqdisho",
    images: ["hero-property"],
    amenities: ["Pool", "Gym", "Concierge", "Parking", "Terrace", "Wine Cellar"],
    petFriendly: true,
    ownerId: "agent-1",
    views: 1247,
    createdAt: "2025-03-15T10:00:00Z",
    featured: true,
  },
  {
    id: "prop-2",
    title: "Villa ballaaran - Hargeysa",
    description: "Villa qoys oo leh beer iyo qolal waaweyn, kuna taalla xaafad cusub oo Hargeysa ah.",
    price: 245000,
    type: "villa",
    listingType: "sale",
    bedrooms: 5,
    bathrooms: 4,
    area: 380,
    address: "Xaafadda New Hargeisa",
    city: "Hargeysa",
    images: ["villa-property"],
    amenities: ["Pool", "Garden", "Theater", "Wine Cellar", "Smart Home", "Guest House"],
    petFriendly: true,
    ownerId: "agent-1",
    views: 892,
    createdAt: "2025-03-10T10:00:00Z",
    featured: true,
  },
  {
    id: "prop-3",
    title: "Guri dabaq ah - Garowe",
    description: "Guri dabaq ah oo ku habboon qoys yar, kuna dhow adeegyada muhiimka ah ee magaalada Garowe.",
    price: 85000,
    type: "apartment",
    listingType: "sale",
    bedrooms: 3,
    bathrooms: 3,
    area: 150,
    address: "Xaafadda Wadajir",
    city: "Garoowe",
    images: ["hero-property"],
    amenities: ["Gym", "Concierge", "Rooftop Lounge", "Parking"],
    petFriendly: false,
    ownerId: "agent-1",
    views: 634,
    createdAt: "2025-02-28T10:00:00Z",
    featured: false,
  },
  {
    id: "prop-4",
    title: "Guri kiro ah - Boosaaso",
    description: "Guri kiro ah oo ballaaran, leh beer yar, kana dhow dekedda iyo adeegyada magaalada Boosaaso.",
    price: 1200,
    type: "house",
    listingType: "rent",
    bedrooms: 5,
    bathrooms: 4,
    area: 260,
    address: "Agagaarka dekedda",
    city: "Boosaaso",
    images: ["villa-property"],
    amenities: ["Pool", "Waterfront", "Smart Home", "Garden", "Dock"],
    petFriendly: true,
    ownerId: "agent-1",
    views: 1089,
    createdAt: "2025-03-20T10:00:00Z",
    featured: true,
  },
  {
    id: "prop-5",
    title: "Guri qoys oo barxad leh - Kismaayo",
    description: "Guri qoys oo leh barxad iyo meel baarkin ah, kuna yaal xaafadda Calanley ee Kismaayo.",
    price: 110000,
    type: "house",
    listingType: "sale",
    bedrooms: 4,
    bathrooms: 4,
    area: 210,
    address: "Xaafadda Calanley",
    city: "Kismaayo",
    images: ["hero-property"],
    amenities: ["Garden", "Terrace", "Fireplace", "Wine Cellar", "Library"],
    petFriendly: true,
    ownerId: "agent-1",
    views: 456,
    createdAt: "2025-01-15T10:00:00Z",
    featured: false,
  },
  {
    id: "prop-6",
    title: "Dhul dhisme - Berbera",
    description: "Dhul fidsan oo ku habboon dhisme guri ama ganacsi, una dhow jidka weyn ee Berbera.",
    price: 70000,
    type: "land",
    listingType: "sale",
    bedrooms: 0,
    bathrooms: 0,
    area: 1000,
    address: "Waddada Berbera",
    city: "Berbera",
    images: ["villa-property"],
    amenities: ["Mountain Views", "Gated Community", "Utilities Ready"],
    petFriendly: true,
    ownerId: "agent-1",
    views: 312,
    createdAt: "2025-02-01T10:00:00Z",
    featured: false,
  },
];

export const SEED_CONVERSATIONS: Conversation[] = [
  {
    id: "conv-1",
    participants: ["user-1", "agent-1"],
    participantNames: { "user-1": "Adiga", "agent-1": "Ayaan Maxamed" },
    propertyId: "prop-1",
    propertyTitle: "Guri dabaq casri ah - Hodan",
    lastMessage: "Waan kuu qaban karaa waqti aad guriga ku soo booqato.",
    lastMessageTime: "2025-03-25T14:30:00Z",
    unreadCount: 1,
  },
  {
    id: "conv-2",
    participants: ["user-1", "agent-1"],
    participantNames: { "user-1": "Adiga", "agent-1": "Ayaan Maxamed" },
    propertyId: "prop-2",
    propertyTitle: "Villa ballaaran - Hargeysa",
    lastMessage: "Iibiyuhu wuu aqbalay dalabkaaga. Hambalyo!",
    lastMessageTime: "2025-03-24T09:15:00Z",
    unreadCount: 0,
  },
];

export const SEED_ALERTS: DalkaAlert[] = [
  {
    id: "alert-1",
    type: "price_drop",
    title: "Qiimaha waa la dhimay",
    body: "Qiimaha guriga Hodan waa la dhimay.",
    propertyId: "prop-1",
    read: false,
    timestamp: "2025-03-25T10:00:00Z",
  },
  {
    id: "alert-2",
    type: "new_listing",
    title: "Guri cusub",
    body: "Guri cusub ayaa laga heli karaa magaalada Boosaaso.",
    propertyId: "prop-4",
    read: false,
    timestamp: "2025-03-24T16:00:00Z",
  },
  {
    id: "alert-3",
    type: "viewing",
    title: "Booqashada waa la xaqiijiyey",
    body: "Booqashada guriga Hargeysa waa la xaqiijiyey.",
    propertyId: "prop-2",
    read: true,
    timestamp: "2025-03-23T11:00:00Z",
  },
  {
    id: "alert-4",
    type: "message",
    title: "Fariin cusub",
    body: "Ayaan Maxamed ayaa fariin ku saabsan guriga Hodan kuu soo dirtay.",
    read: true,
    timestamp: "2025-03-22T08:00:00Z",
  },
];
